
###GET
GET localhost:8006/api/coupon/policy
###POST
POST localhost:8006/api/coupon/policy/register
Content-Type: application/json

{
  "couponPolicyDescription": "description",
  "discountType": "AMOUNTDISCOUNT",
  "discountValue": 10000,
  "minPurchaseAmount": 0,
  "maxDiscountAmount": 10000,
  "id": 1,
  "typeName": "카테고리"
}
