### GET request to example server
GET localhost:8006/api/coupon
X-User-Id:26

### GET mypage
GET localhost:8006/api/coupon/myPage?page=0&size=1
X-User-Id:181
### Post request
POST localhost:8006/api/coupon/register/3
Content-Type: application/json

{
  "clientId": 1,
  "expirationDate": "2024-06-05T15:55:08",
  "couponTypeId": 1,
  "status": "AVAILABLE"

}

### put Test
PUT localhost:8006/api/coupon/update
Content-Type: application/json

{
  "couponId": 2
}



###POST
POST localhost:8006/api/client/welcome/1

###put
PUT localhost:8006/api/coupon/refund?couponId=27

### get
GET localhost:8006/api/coupon/policy


