### GET request to example server
GET localhost:8006/coupon/123

### Post request
POST localhost:8006/admin/coupon/register/1
Content-Type: application/json

{
  "clientId": 123,
  "expirationDate": "2024-06-05T15:55:08",
  "couponPolicyId": 1,
  "couponTypeId": 1,
  "status": "AVAILABLE"

}